//Announcements
export const FETCH_ANNOUNCEMENTS_REQUEST = 'FETCH_ANNOUNCEMENTS_REQUEST';
export const FETCH_ANNOUNCEMENTS_SUCCESS = 'FETCH_ANNOUNCEMENTS_SUCCESS';
export const FETCH_ANNOUNCEMENTS_FAIL = 'FETCH_ANNOUNCEMENTS_FAIL';

//Events
export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_FAIL';

//Attendance
export const FETCH_ATTENDANCE_REQUEST = 'FETCH_ATTENDANCE_REQUEST';
export const FETCH_ATTENDANCE_SUCCESS = 'FETCH_ATTENDANCE_SUCCESS';
export const FETCH_ATTENDANCE_FAIL = 'FETCH_ATTENDANCE_FAIL';

//Directory
export const FETCH_DIRECTORY_REQUEST = 'FETCH_DIRECTORY_REQUEST';
export const FETCH_DIRECTORY_SUCCESS = 'FETCH_DIRECTORY_SUCCESS';
export const FETCH_DIRECTORY_FAIL = 'FETCH_DIRECTORY_FAIL';

//Gallery
export const FETCH_GALLERY_REQUEST = 'FETCH_GALLERY_REQUEST';
export const FETCH_GALLERY_SUCCESS = 'FETCH_GALLERY_SUCCESS';
export const FETCH_GALLERY_FAIL = 'FETCH_GALLERY_FAIL';
